### ISSUE TITLE
Stuck on thinking

### ISSUE THREAD

**Issue by slyeet03** [SenZmaKi/Sengpt#1]
I wrote a prompt to generate an autohotkey script, and it is stuck on `Thinking..` for the last 10 minutes. 

The prompt i wrote: `sengpt give me a autohot key script using version2 which will run a command in terminal and then keep the terminal open, i want that script to run when i press alt+7 -i`

**Comment by slyeet03** [comment]
Tried it in another terminal, still getting the same issue.

**Comment by slyeet03** [comment]
I ran it again and it still got stuck after the second prompt
![image](https://github.com/SenZmaKi/Sengpt/assets/145686556/d68154e5-6a90-49cc-b36b-9f3968e9d861)

**Comment by SenZmaKi** [comment]
It seems like it's stuck at the prompt section, which means it's probably an issue with [re_gpt](https://github.com/Zai-Kun/reverse-engineered-chatgpt), which sengpt currently runs on a modified version of, but re_gpt is still pretty unstable so you'll run into weird behaviour, but of course with time as the library matures and stabilises so will sengpt

**Comment by slyeet03** [comment]
Oh, I see. Thanks for clarifying.
